apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-web-app.frontend.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "my-web-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  selector:
    {{- include "my-web-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.port }}
  type: {{ .Values.frontend.service.type }}